roles:
  - src: https://github.com/ait-testbed/ansible-manage_unattended_upgrades.git
    version: v0.0.0
    name: manage_unattended_upgrades
  - src: https://github.com/ait-testbed/atb-ansible-rootkeys.git
    version: v1.0.0
    name: rootkeys
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-aecidtools.git
    version: v1.1.0
    name: aecidtools
  - src: https://github.com/ait-testbed/ansible-mate-desktop.git
    version: v1.2.1
    name: mate-desktop
  - src: https://github.com/ait-testbed/atb-ansible-novnc.git
    version: v1.0.0
    name: novnc
  - src: https://github.com/ait-testbed/attackmate-ansible.git
    version: v1.4.0
    name: attackmate
