roles:
  - src: https://github.com/ait-testbed/ansible-manage_unattended_upgrades.git
    version: v0.0.0
    name: manage_unattended_upgrades
  - src: https://github.com/ait-testbed/ansible-auditd.git
    version: v1.1
    name: auditd
  - src: https://github.com/ait-testbed/atb-ansible-dockerce.git
    version: v0.1.0
    name: atb-ansible-dockerce
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-aecidtools.git
    version: v1.1.0
    name: aecidtools
  - src: https://github.com/ait-testbed/atb-ansible-nextcloudrce.git
    version: v1.0.4
    name: nextcloudrce
  - src: https://github.com/ait-testbed/atb-ansible-vulndockerd.git
    version: v1.0.0
    name: vulndockerd
  - src: https://github.com/ait-testbed/atb-ansible-wazuh_agent.git
    version: v0.9.0
    name: wazuh_agent
  - src: https://github.com/ait-testbed/atb-ansible-collectd.git
    version: v1.0.2
    name: collectd
  - src: https://github.com/ait-testbed/atb-ansible-acct.git
    version: v1.0.0
    name: acct
