roles:
  - src: https://github.com/ait-testbed/ansible-manage_unattended_upgrades.git
    version: v1.0.0
    name: manage_unattended_upgrades
  - src: https://github.com/ait-testbed/ansible-auditd.git
    version: v1.1
    name: auditd
  - src: https://github.com/ait-testbed/atb-ansible-rootkeys.git
    version: v1.0.0
    name: rootkeys
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-aecidtools.git
    version: v1.1.0
    name: aecidtools
  - src: https://github.com/ait-testbed/ansible-mate-desktop.git
    version: v1.2.1
    name: mate-desktop
  - src: https://github.com/ait-testbed/atb-ansible-weaklinuxuser.git
    version: v1.0.2
    name: weaklinuxuser
  - src: https://github.com/ait-testbed/atb-ansible-hostname.git
    version: v1.0.0
    name: hostname
  - src: https://github.com/ait-testbed/ansible-role-samba.git
    version: v2.7.2
    name: samba
  - src: https://github.com/ait-testbed/atb-ansible-acct.git
    version: v1.0.0
    name: acct
  - src: https://github.com/ait-testbed/atb-ansible-collectd.git
    version: v1.0.2
    name: collectd
  - src: https://github.com/ait-testbed/atb-ansible-ftploginjob.git
    version: v1.0.1
    name: ftploginjob
  - src: https://github.com/ait-testbed/atb-ansible-zippeddata.git
    version: v1.0.1
    name: zippeddata
  - src: https://github.com/ait-testbed/atb-ansible-healthcheck.git
    version: v1.0.0
    name: healthcheck
  - src: https://github.com/ait-testbed/atb-ansible-nfsserver.git
    version: v1.0.0
    name: nfsserver
  - src: https://github.com/ait-testbed/atb-ansible-customdpkg.git
    version: v1.0.3
    name: customdpkg
  - src: https://github.com/ait-testbed/atb-ansible-rootkeys.git
    version: v1.0.0
    name: rootkeys
  - src: https://github.com/ait-testbed/atb-ansible-puppetclient.git
    version: v1.0.1
    name: puppetclient
  - src: https://github.com/ait-testbed/atb-ansible-disableresolved
    version: v1.0.0
    name: disableresolved
  - src: https://github.com/ait-testbed/atb-ansible-wazuh_agent.git
    version: v0.9.0
    name: wazuh_agent
