roles:
  - src: https://github.com/ait-testbed/ansible-auditd.git
    version: v1.1
    name: auditd
  - src: https://github.com/ait-testbed/atb-ansible-dnsmasq.git
    version: v1.1.3
    name: dnsmasq
  - src: https://github.com/ait-testbed/atb-ansible-suricata.git
    version: v1.1.8
    name: suricata
  - src: https://github.com/whotwagner/ansible-role-shorewall.git
    version: v2.0.3
    name: shorewall
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-weaklinuxuser.git
    version: v1.0.2
    name: weaklinuxuser
  - src: https://github.com/ait-testbed/atb-ansible-squidproxy.git
    version: v1.0.3
    name: squidproxy
  - src: https://github.com/ait-testbed/atb-ansible-filebeat.git
    version: v0.9.3
    name: filebeat
  - src: https://github.com/ait-testbed/atb-ansible-aecidtools.git
    version: v1.1.0
    name: aecidtools
  - src: https://github.com/ait-testbed/atb-ansible-wazuh_agent.git
    version: v0.9.0
    name: wazuh_agent
  - src: https://github.com/ait-testbed/atb-ansible-collectd.git
    version: v1.0.2
    name: collectd
  - src: https://github.com/ait-testbed/atb-ansible-acct.git
    version: v1.0.0
    name: acct
  - src: https://github.com/ait-testbed/ansible-manage_unattended_upgrades.git
    version: v1.0.0
    name: manage_unattended_upgrades
