roles:
  - src: https://github.com/ait-cs-IaaS/ansible-auditd.git
    version: v1.1
    name: auditd
  - src: https://github.com/ait-testbed/atb-ansible-dnsmasq.git
    version: v1.1.3
    name: dnsmasq
  - src: https://github.com/ait-testbed/atb-ansible-suricata.git
    version: v1.1.7
    name: suricata
  - src: https://github.com/whotwagner/ansible-role-shorewall.git
    version: v2.0.3
    name: shorewall
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-weaklinuxuser.git
    version: v1.0.2
    name: weaklinuxuser
  - src: https://github.com/ait-testbed/atb-ansible-squidproxy.git
    version: v1.0.3
    name: squidproxy
  - src: https://github.com/ait-testbed/atb-ansible-filebeat.git
    version: v0.9.2
    name: filebeat

