roles:
  - src: https://github.com/ait-testbed/atb-ansible-metasploit.git
    version: v1.5
    name: metasploit
  - src: https://github.com/ait-testbed/atb-ansible-disableresolved
    version: v1.0.0
    name: disableresolved
  - src: https://github.com/ait-testbed/atb-ansible-postexploit.git
    version: v1.2.3
    name: postexploit
  - name: l50.sliver
    version: v1.0.1
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-aecidtools.git
    version: v1.1.0
    name: aecidtools
  - src: https://github.com/ait-testbed/atb-ansible-seclists.git
    version: v0.0.1
    name: seclists
  - src: https://github.com/ait-testbed/attackmate-ansible.git
    version: v1.2.0
    name: attackmate
  - src: https://github.com/ait-testbed/ansible-manage_unattended_upgrades.git
    version: v0.0.0
    name: manage_unattended_upgrades
  - src: https://github.com/ait-testbed/ansible-mate-desktop.git
    version: v1.2.1
    name: mate-desktop
  - src: https://github.com/ait-testbed/atb-ansible-novnc.git
    version: v1.0.0
    name: novnc
  - src: https://github.com/ait-testbed/atb-ansible-rustdesk.git
    version: v1.0.0
    name: rustdesk
  - src: https://github.com/ait-testbed/atb-ansible-veiltransfer.git
    version: v1.0.0
    name: veiltransfer
  - src: https://github.com/ait-testbed/atb-ansible-acct.git
    version: v1.0.0
    name: acct
