roles:
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-aecidtools.git
    version: v1.1.0
    name: aecidtools
  - src: https://github.com/ait-testbed/ansible-mate-desktop.git
    version: v1.2.1
    name: mate-desktop
  - src: https://github.com/ait-testbed/atb-ansible-novnc.git
    version: v1.0.0
    name: novnc
  - src: https://github.com/ait-testbed/atb-ansible-weaklinuxuser.git
    version: v1.0.2
    name: weaklinuxuser
  - src: https://github.com/ait-testbed/atb-ansible-thunderbird.git
    version: main
    name: thunderbird
  - src: https://github.com/ait-testbed/acr-ansible-libreoffice-and-macro-security.git
    version: master
    name: libreoffice
  - src: https://github.com/ait-testbed/atb-ansible-firefox-home.git
    version: main
    name: firefox-home
  - src: https://github.com/ait-testbed/ansible-manage_unattended_upgrades.git
    version: v1.0.0
    name: manage_unattended_upgrades
  - src: https://github.com/ait-testbed/ansible-auditd.git
    version: v1.1
    name: auditd
  - src: https://github.com/ait-testbed/atb-ansible-collectd.git
    version: v1.0.2
    name: collectd
  - src: https://github.com/ait-testbed/atb-ansible-acct.git
    version: v1.0.0
    name: acct
  - src: https://github.com/ait-testbed/atb-ansible-wazuh_agent.git
    version: v0.9.0
    name: wazuh_agent
