collections:
  - src: https://github.com/ansible-collections/community.docker.git
    version: 2.7.8
    name: community.docker
roles:
  - src: https://github.com/ait-testbed/ansible-manage_unattended_upgrades.git
    version: v0.0.0
    name: manage_unattended_upgrades
  - src: https://github.com/ait-testbed/atb-ansible-aeciduser.git
    version: v1.0.0
    name: aeciduser
  - src: https://github.com/ait-testbed/atb-ansible-aecidtools.git
    version: v1.1.0
    name: aecidtools
  - src: https://github.com/geerlingguy/ansible-role-docker.git
    version: 7.1.0
    name: docker
  - src: https://github.com/ait-testbed/atb-ansible-ghostserver.git
    version: v1.0.0
    name: ghostsserver
  - src: https://github.com/ait-testbed/atb-ansible-acct.git
    version: v1.0.0
    name: acct
