# Ansible Collection  requirements
collections:
  # openstack modules for inventory src
  - name: openstack.cloud
    version: 1.7.0

roles:
  - name: l50.sliver
    version: v1.0.1
  - name: kyoushi-gather
    src: https://github.com/ait-testbed/atb-kyoushi-gather.git
    version: v0.9.1
